# github: [metadata]
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate
#
#
theme: jekyll-theme-minimal


baseurl: "/bubbleShooter"
name: A Bubble Shooter
